version: '3'
services:
  web:
    image: nginx:1.19
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx/
    links:
      - php

  php:
    image: php-fpm-lavaral:7.4.0
    volumes:
      - ./:/code
